name: Build Fabric Server

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Fabric Server Jar
        run: |
          mkdir out
          curl -o out/fabric-server-1.21.6.jar \
            https://meta.fabricmc.net/v2/versions/loader/1.21.6/0.16.9/1.0.2/server/jar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: fabric-server
          path: out/fabric-server-1.21.6.jar
